<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ADManager.Plugins</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ADManagerFileSystem\ADManagerFileSystem.csproj" />
    <ProjectReference Include="..\ADManagerGlobal\ADManagerGlobal.csproj" />
  </ItemGroup>
</Project>
